diff --git a/tests/ovpn-cli/Makefile b/tests/ovpn-cli/Makefile
index 169f046..1dfd13d 100644
--- a/tests/ovpn-cli/Makefile
+++ b/tests/ovpn-cli/Makefile
@@ -10,6 +10,8 @@ VAR_CFLAGS = -I/usr/include/libnl3
 endif
 CFLAGS += $(VAR_CFLAGS)
 
+CFLAGS += -I../../include/uapi -I..
+
 MTLS_LDLIBS= $(shell pkg-config --libs mbedcrypto-3 mbedtls-3 2>/dev/null)
 ifeq ($(MTLS_LDLIBS),)
 MTLS_LDLIBS = -lmbedtls -lmbedcrypto
@@ -48,4 +50,9 @@ TEST_PROGS := \
 
 TEST_GEN_FILES := ovpn-cli
 
-include ../../lib.mk
+all: $(TEST_GEN_FILES)
+
+clean:
+	rm -f $(TEST_GEN_FILES)
+
+.PHONY: all clean
