---
name: virtme-ng selftests

"on":
  workflow_dispatch:
  schedule:
    - cron: "17 7 * * *"

permissions:
  contents: read

jobs:
  vng-selftests:
    uses: mandelbitdev/kmod-ci/.github/workflows/out-of-tree-vng.yml@main
    with:
      ci-repository: mandelbitdev/kmod-ci
      cache-prefix: ovpn-backports
      guest-script: ci/run-selftests.sh
      prepare-command: ./backports-ctl.sh get-ovpn -t
    secrets:
      RHEL_ORG_ID: ${{ secrets.RHEL_ORG_ID }}
      RHEL_ACTIVATION_KEY: ${{ secrets.RHEL_ACTIVATION_KEY }}
